export const GET_PRODUCTS_DATA_REQUEST = "GET_PRODUCTS_DATA_REQUEST";
export const GET_PRODUCTS_DATA_SUCCESS = "GET_PRODUCTS_DATA_SUCCESS";
export const GET_PRODUCTS_DATA_FAILURE = "GET_PRODUCTS_DATA_FAILURE";

export const GET_TOTAL_COUNT = "GET_TOTAL_COUNT";

export const POST_ADD_TO_CART_REQUEST = "POST_ADD_TO_CART_REQUEST";
export const POST_ADD_TO_CART_SUCCESS = "POST_ADD_TO_CART_SUCCESS";
export const POST_ADD_TO_CART_FAILURE = "POST_ADD_TO_CART_FAILURE";

export const GET_USER_CART_DATA_REQUEST = "GET_USER_CART_DATA_REQUEST";
export const GET_USER_CART_DATA_SUCCESS = "GET_USER_CART_DATA_SUCCESS";
export const GET_USER_CART_DATA_FAILURE = "GET_USER_CART_DATA_FAILURE";

export const PATCH_CART_DATA_REQUEST = "PATCH_CART_DATA_REQUEST";
export const PATCH_CART_DATA_SUCCESS = "PATCH_CART_DATA_SUCCESS";
export const PATCH_CART_DATA_FAILURE = "PATCH_CART_DATA_FAILURE";


export const EMPTY_CART_DATA_REQUEST = "EMPTY_CART_DATA_REQUEST";
export const EMPTY_CART_DATA_SUCCESS = "EMPTY_CART_DATA_SUCCESS";
export const EMPTY_CART_DATA_FAILURE = "EMPTY_CART_DATA_FAILURE";



export const DELETE_CART_DATA_REQUEST = "DELETE_CART_DATA_REQUEST";
export const DELETE_CART_DATA_SUCCESS = "DELETE_CART_DATA_SUCCESS";
export const DELETE_CART_DATA_FAILURE = "DELETE_CART_DATA_FAILURE";
